Documenting for Commit message: I have made no changes to the application code, but changes to the configuration settings of IntelliJ, but I am still not able to get it to free compile, and it produces the following message when I run the main class…
/Users/michaellittle/Library/Java/JavaVirtualMachines/openjdk-23.0.1/Contents/Home/bin/java --module-path ${/Users/michaellittle/04MyProjects_LBOOK/01Resources/javafx-sdk-23.0.1/lib} --add-modules javafx.controls,javafx.fxml -javaagent:/Applications/IntelliJ IDEA.app/Contents/lib/idea_rt.jar=53014:/Applications/IntelliJ IDEA.app/Contents/bin -agentpath:/private/var/folders/g_/m40_jsjj2jlbygttg3wdlxtc0000gn/T/idea_libasyncProfiler_dylib_temp_folder/libasyncProfiler.dylib=start,jfr,event=wall,interval=10ms,jfrsync=profile,cstack=no,file=/Users/michaellittle/IdeaSnapshots/main_2024_12_06_155917.jfr,log=/private/var/folders/g_/m40_jsjj2jlbygttg3wdlxtc0000gn/T/main_2024_12_06_155917.jfr.log.txt,logLevel=DEBUG -Dfile.encoding=UTF-8 -Dsun.stdout.encoding=UTF-8 -Dsun.stderr.encoding=UTF-8 -classpath /Users/michaellittle/.m2/repository/org/openjfx/javafx-controls/17.0.6/javafx-controls-17.0.6.jar:/Users/michaellittle/.m2/repository/org/openjfx/javafx-graphics/17.0.6/javafx-graphics-17.0.6.jar:/Users/michaellittle/.m2/repository/org/openjfx/javafx-base/17.0.6/javafx-base-17.0.6.jar:/Users/michaellittle/.m2/repository/org/openjfx/javafx-fxml/17.0.6/javafx-fxml-17.0.6.jar:/Users/michaellittle/04MyProjects_LBOOK/01Resources/javafx-sdk-23.0.1/lib/javafx-swt.jar:/Users/michaellittle/04MyProjects_LBOOK/01Resources/javafx-sdk-23.0.1/lib/javafx.media.jar:/Users/michaellittle/04MyProjects_LBOOK/01Resources/javafx-sdk-23.0.1/lib/javafx.swing.jar:/Users/michaellittle/04MyProjects_LBOOK/01Resources/javafx-sdk-23.0.1/lib/javafx.web.jar -m dev.research.devcode/dev.research.devcode.HelloApplication
Error occurred during initialization of boot layer
java.lang.module.FindException: Module javafx.controls not found

Process finished with exit code 1